version: '3.1'

services:
  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: WishListUser
      MYSQL_PASSWORD: 53cr37
      MYSQL_DATABASE: wishlist
    ports:
      - 3306:3306
    command: ['mysqld', '--character-set-server=utf8', '--collation_server=utf8_unicode_ci']
